export const SentItemOrder = [
    "Date",
    "Project",
    "CableNumber",
    "Approver",
    "Status"
   ]
   export const CreateNewOrder = [
    "CABLENUM",  
    "FORMDEV_NAME", 
    "FUNC", 
    "CABLETYPE", 
    "ORIGIN_LOC", 
    "ORIGIN_RACK", 
    "ORIGIN_SIDE", 
    "ORIGIN_ELE", 
    "ORIGIN_SLOT", 
    "ORIGIN_CONNUM", 
    "ORIGIN_PINLIST", 
    "ORIGIN_CONNTYPE", 
    "ORIGIN_STATION", 
    "ORIGIN_INSTR", 
    "DEST_LOC", 
    "DEST_RACK",
    "DEST_SIDE", 
    "DEST_ELE", 
    "DEST_SLOT", 
    "DEST_CONNUM", 
    "DEST_PINLIST", 
    "DEST_CONNTYPE", 
    "DEST_STATION", 
    "DEST_INSTR", 
    "LENGTH", 
    "ROUTING", 
    "REVISION", 
    "JOBNUM", 
    "DWGNUM", 
    "DRAWING_TITLE", 
    "ENTEREDBY", 
    "USERID_LIST_TITLE",
    "AREACODE", 
    "MIN_LENGTH", 
    "MAX_LENGTH", 
    "ADDNL_LENGTH", 
    "PHASE", 
    "BEAM_AREA", 
    "SECTOR_GROUP",
    "SECTOR_AREA_SOURCE",
    "SECTOR_AREA_DEST", 
    "PENETRATION", 
    "PENETRATION_2", 
   ]
   export const CableListingOrder = [
    "Project",
    "CableNumber",
    "Status"
   ]
   export const orderApprover = [
    "Project",
    "Editor",
    "CableNumber",
    "FormalDeviceName",
    "FormalDevice",
    // "CableFunction",
    "CableType",
    // "OriginLoc",
    // "OriginRack",
    // "OriginSide",
    // "OriginEle",
    // "OriginSlot",
    // "OriginConn",
    // "OriginPinlist",
    // "OriginConnType",
    // "OriginStation",
    // "OriginIns",
    // "DestLoc",
    // "DestRack",
    // "DestSide",
    // "DestEle",
    // "DestSlot",
    // "DestConn",
    // "DestPinlist",
    // "DestConnType",
    // "DestStation",
    // "DestIns",
    // "Length",
    // "Routing",
    // "Revision",
    // "Job",
    // "Drawing",
    // "DrawingTitle",
    // "UserId",
    // "ListTitle",
    // "AreaCode"
   ]
// export const uploadedOrder = [
//     'STATUS',
//     'CABLENUM',
//     'AREACODE',
//     'CABLETYPE',
//     'CONNTYPE',
//     'JOBNUM',
//     'ENTEREDBY',
//     'DATEENT',
//     'FUNC',
//     'ACTIONREQ',
//     'SYSTEM',
//     'LENGTH',
//     'ROUTING',
//     'LIST_NO',
//     'DWGNUM',
//     'LOC',
//     'RACK',
//     'SIDE',
//     'ELE',
//     'SLOT',
//     'CONNUM',
//     'PINLIST',
//     'STATION',
//     'INSTR',
//     'STATION_OLD',
//     'CREATED_BY',
//     'CREATED_DATE',
//     'MODIFIED_BY',
//     'MODIFIED_DATE',
//     'DRAWING_TITLE']
    export const CreateCableOrder = [
'CABLENUM',
'AREACODE',
'CABLETYPE',
'ORIGIN_CONNTYPE',
'DEST_CONNTYPE',
'JOBNUM',
'FUNC',
'SYSTEM',
'LENGTH',
'ROUTING',
'LIST_NO',
'DWGNUM',
'DRAWING_TITLE',
'ORIGIN_LOC',
'ORIGIN_RACK',
'ORIGIN_SIDE',
'ORIGIN_ELE',
'ORIGIN_SLOT',
'ORIGIN_CONNUM',
'ORIGIN_PINLIST',
'ORIGIN_STATION',
'ORIGIN_INSTR',
'STATION_OLD',
'DEST_LOC',
'DEST_RACK',
'DEST_SIDE',
'DEST_ELE',
'DEST_SLOT',
'DEST_CONNUM',
'DEST_PINLIST',
'DEST_STATION',
'DEST_INSTR',
'FORMDEV_NAME',
'PHASE',
'BEAM_AREA',
'SECTOR_GROUP',
'SECTOR_AREA_SOURCE',
'SECTOR_AREA_DEST',
'PENETRATION',
'PENETRATION_2',
'MIN_LENGTH',
'MAX_LENGTH',
'ADDNL_LENGTH',
'REVISION']

export const tableOrder = [
    "Project",
    "Status",
    "CableNumber",
    "FormalDeviceName",
    // "FormalDevice",
    // "CableFunction",
    "CableType",
    // "OriginLoc",
    // "OriginRack",
    // "OriginSide",
    // "OriginEle",
    // "OriginSlot",
    // "OriginConn",
    // "OriginPinlist",
    // "OriginConnType",
    // "OriginStation",
    // "OriginIns",
    // "DestLoc",
    // "DestRack",
    // "DestSide",
    // "DestEle",
    // "DestSlot",
    // "DestConn",
    // "DestPinlist",
    // "DestConnType",
    // "DestStation",
    // "DestIns",
    // "Length",
    // "Routing",
    // "Revision",
    // "Job",
    // "Drawing",
    // "DrawingTitle",
    // "UserId",
    // "ListTitle",
    // "AreaCode"
]
export const orderApproverModal = [
    "Feedback",
    "Project",
    "Editor",
    "CableNumber",
    "FormalDeviceName",
    "FormalDevice",
    "CableFunction",
    "CableType",
    "OriginLoc",
    "OriginRack",
    "OriginSide",
    "OriginEle",
    "OriginSlot",
    "OriginConn",
    "OriginPinlist",
    "OriginConnType",
    "OriginStation",
    "OriginIns",
    "DestLoc",
    "DestRack",
    "DestSide",
    "DestEle",
    "DestSlot",
    "DestConn",
    "DestPinlist",
    "DestConnType",
    "DestStation",
    "DestIns",
    "Length",
    "Routing",
    "Revision",
    "Job",
    "Drawing",
    "DrawingTitle",
    "UserId",
    "ListTitle",
    "AreaCode"
   ]
   export const historyOrder = ['CABLENUM', 'ENTEREDBY','DATEENT','CREATED_BY', 'CREATED_DATE', 'MODIFIED_BY', 'MODIFIED_DATE','AREACODE']
   export const deny = ['DATEENT','CREATED_DATE', 'MODIFIED_DATE']
   export const inventoryOrder = [
    "CABLENUM",  
    "FORMDEV_NAME", 
    "FUNC", 
    "CABLETYPE", 
    "ORIGIN_LOC", 
    "ORIGIN_RACK", 
    "ORIGIN_SIDE", 
    "ORIGIN_ELE", 
    "ORIGIN_SLOT", 
    "ORIGIN_CONNUM", 
    "ORIGIN_PINLIST", 
    "ORIGIN_CONNTYPE", 
    "ORIGIN_STATION", 
    "ORIGIN_INSTR", 
    "DEST_LOC", 
    "DEST_RACK",
    "DEST_SIDE", 
    "DEST_ELE", 
    "DEST_SLOT", 
    "DEST_CONNUM", 
    "DEST_PINLIST", 
    "DEST_CONNTYPE", 
    "DEST_STATION", 
    "DEST_INSTR", 
    "LENGTH", 
    "ROUTING", 
    "REVISION", 
    "JOBNUM", 
    "DWGNUM", 
    "DRAWING_TITLE", 
    "ENTEREDBY", 
    "USERID_LIST_TITLE",
    "AREACODE", 
    "MIN_LENGTH", 
    "MAX_LENGTH", 
    "ADDNL_LENGTH", 
    "PHASE", 
    "BEAM_AREA", 
    "SECTOR_GROUP",
    "SECTOR_AREA_SOURCE",
    "SECTOR_AREA_DEST", 
    "PENETRATION", 
    "PENETRATION_2",  
      
   ]
   export const userOrder = [
    'USERNAME',
    'PROJECTS'
   ]
   export const projectOrder = [
    'PROJECT_NAME',
    'PREFIX',
    'NUM_CABLES',
    'ASSIGNED_USERS'
   ]

   export const SimpleCableOrder = [
    "CABLENUM",
    "STATUS"
   ]



   export const uploadedOrder = [
'STATUS',
"CABLENUM", 
'ENTEREDBY',
'DATEENT',
"FORMDEV_NAME", 
"FUNC", 
"CABLETYPE", 
"ORIGIN_LOC", 
"ORIGIN_RACK", 
"ORIGIN_SIDE", 
"ORIGIN_ELE", 
"ORIGIN_SLOT", 
"ORIGIN_CONNUM", 
"ORIGIN_PINLIST", 
"ORIGIN_CONNTYPE", 
"ORIGIN_STATION", 
"ORIGIN_INSTR", 
"DEST_LOC", 
"DEST_RACK",
"DEST_SIDE", 
"DEST_ELE", 
"DEST_SLOT", 
"DEST_CONNUM", 
"DEST_PINLIST", 
"DEST_CONNTYPE", 
"DEST_STATION", 
"DEST_INSTR", 
"LENGTH", 
"ROUTING", 
"REVISION", 
"JOBNUM", 
"DWGNUM", 
"DRAWING_TITLE", 
"USERID_LIST_TITLE",
"AREACODE", 
"MIN_LENGTH", 
"MAX_LENGTH", 
"ADDNL_LENGTH", 
"PHASE", 
"BEAM_AREA", 
"SECTOR_GROUP",
"SECTOR_AREA_SOURCE",
"SECTOR_AREA_DEST", 
"PENETRATION", 
"PENETRATION_2", 

   ]

 

   export const keys = {
    'CABLENUM':"Cable #",
'AREACODE':"Area Code", 
'CABLETYPE':"CableType",
'ORIGIN_CONNTYPE':"Origin Conn Type",
'DEST_CONNTYPE':"Dest Conn Type",
'JOBNUM': "Job #",
'FUNC': "CableFunction",
'ROUTING': "Routing",
'DWGNUM':"Drawing #",
'DRAWING_TITLE':"Drawing Title",
'ORIGIN_LOC': "Origin Loc",
'ORIGIN_RACK':"Origin Rack",
'ORIGIN_SIDE':"Origin Side",
'ORIGIN_ELE':"Origin Ele",
'ORIGIN_SLOT':"Origin Slot",
'ORIGIN_CONNUM':"Origin Conn #",
'ORIGIN_PINLIST':"Origin Pinlist",
'ORIGIN_STATION':"Origin Station",
'ORIGIN_INSTR':"Origin Ins",
'DEST_LOC':"Dest Loc",
'DEST_RACK':"Dest Rack",
'DEST_SIDE':"Dest Side",
'DEST_ELE':"Dest Ele",
'DEST_SLOT':"Dest Slot",
'DEST_CONNUM':"Dest Conn #",
'DEST_PINLIST':"Dest Pinlist",
'DEST_STATION':"Dest Station",
'DEST_INSTR':"Dest Ins",
'FORMDEV_NAME':"FormalDevice Name",
'PHASE':"Phase",
'BEAM_AREA':"Beamline Area",
'SECTOR_GROUP':"Sector Group",
'SECTOR_AREA_SOURCE':"Sector Area Source",
'SECTOR_AREA_DEST':"Sector Area Dest",
'PENETRATION':"Penetration",
'PENETRATION_2':"Penetration II",
'MIN_LENGTH':"Min Length",
'MAX_LENGTH':"Max Length",
'ADDNL_LENGTH':"Addnl Length",
'REVISION':"Revision"
   }
   export const deleteKeys = [
    "ENTEREDBY","DATEENT","ACTIONREQ","SYSTEM","LENGTH","LIST_NO","CABLEINV_ID","CREATED_BY","CREATED_DATE","MODIFIED_BY","MODIFIED_DATE","STATUS","STATION_OLD","APPROVERS","USERID_LIST_TITLE","DUPLICATES","ORIGIN_TYPEERR","DEST_TYPEERR","select",
   ]

