name: Build For Pull Request
on: 
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - main
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
jobs:
    build:
        uses: slaclab/SMCAPTAR_FRONT-Deployment/.github/workflows/build-test.yml@main
        secrets: inherit
