name: Build For Deployment
on: 
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true
jobs:
    build:
        uses: eed-web-application/SMCAPTAR_FRONT-Deployment/.github/workflows/build-test-create.yml@main
        secrets: inherit
